### ISSUE TITLE
i cannot install to my server

### ISSUE THREAD

**Issue by yharby** [Liinkiing/multiplayer-piano#12]
i cannot install to my server and i wish to integrate this with BigBlueButton to teach music throw online lessons with low latency and good sound , thank you !
https://github.com/bigbluebutton/bigbluebutton

**Comment by Liinkiing** [comment]
You would need the node backend code to make it work and fully integrates with your custom solution! I would love to see it in action, but the server is in a private repository, because at the time I've made this little side project, I was learning socket.io so it may not be a good example. But if you want I can send you a download link of the repository ZIP, just give me an email or something I could send you the link! 

If you use it in your product, it would be great if you could have some informations about this repository and what are you using, in one line or two! Just to have some kind of shoutout, I will be grateful!

**Comment by yharby** [comment]
Thank you very much
