### ISSUE TITLE
Sustain pedal not working

### ISSUE THREAD

**Issue by david4599** [Liinkiing/multiplayer-piano#9]
When I push on my sustain pedal, the E5 note is triggered and notes are not maintained so I guess the pedal is not implemented. Do you plan to add this function?

**Comment by david4599** [comment]
After looking at the code, I saw that you already implemented the sustain pedal but it was not working for me. I found that the MIDI sustain value my keyboard sent was 179 when I pushed on it and 176 when my keyboard played a midi file.

So I changed the line 11 of MIDIMessage.js from `if (data[0] === 187) {` to `if (data[0] === 179 || data[0] === 176) {` and it worked.

**Comment by Liinkiing** [comment]
Oh sorry I just saw your message (thanks new Github notifications 😅) and for the sustain pedal, It looks like it may differ from devices. For example, I have a Keystation 88 and the pedal just works fine. But I should have used MIDI.js, I didn't know it existed when I was fiddling with this application, because my implementation of MIDI is very naive :/

Great to hear that it works for you when you change the value

**Comment by Liinkiing** [comment]
I will change the code to support your value, do you want to make a PR or I'll do it myself, as you prefer

**Comment by david4599** [comment]
So apparently the same message can be triggered by different values depending on devices used, not for the keys but for sustain and other controllers I guess, that's a good thing to know.
I'll let you make the change.

**Comment by Liinkiing** [comment]
Fixed in dd549dfb0735e12058084a0183b5e8cb3a4ec1d4 👍 Thanks for your feedback!
